# The image will be at ghcr.io/yourusername/name
name: desktop-image

# The native container image to build on top of
# images. 
# Warning: Non-uBlue images might function unexpectedly
base-container: ghcr.io/ublue-os/silverblue-nvidia

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this). 
fedora-version: 38

# This description will be visible in the container metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - rpm-build # needed to build rpms
  # -- mangohud deps --
  - meson
  - gcc
  - gcc-c++
  - libX11-devel
  - glslang
  - python3-mako
  - mesa-libGL-devel
  - libXNVCtrl-devel
  - dbus-devel
  # -- mangohud deps --
  - python3-pip # needed for yafti (the first boot installer)
  - gjs-devel
  - langpacks-en
  - libgda 
  - libgda-sqlite 
  - util-linux-user 
  - zsh
  - gamescope

# These Flatpaks (from flathub) will be available for install on boot
# this is just an example selection.
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - org.mozilla.firefox
  - org.mozilla.Thunderbird
  - com.mattjakeman.ExtensionManager
  - org.libreoffice.LibreOffice
  - org.gnome.DejaDup
  - org.gustavoperedo.FontDownloader
  - com.github.tchx84.Flatseal
  - io.github.celluloid_player.Celluloid
  - com.visualstudio.code
  - com.valvesoftware.Steam
